apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-test
  namespace: jettisonproj
spec:
  args:
  - name: service-name
  metrics:
  - name: integration-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            spec:
              containers:
              - name: integration-test
                image: ghcr.io/jettisonproj/rollouts-demo-integration-test:85c7afa3c61e75bf9d76ba305d82ce287b12741b
                args:
                - "./integration-test.sh"
                - "http://{{args.service-name}}"
              restartPolicy: Never
