apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-test
  namespace: jettisonproj
spec:
  args:
  - name: service-name
  metrics:
  - name: integration-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            spec:
              containers:
              - name: integration-test
                image: ghcr.io/jettisonproj/rollouts-demo-integration-test:64c663982989986216ae328c563e58f87cfda83e
                args:
                - "./integration-test.sh"
                - "http://{{args.service-name}}"
              restartPolicy: Never
