apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-test
  namespace: jettisonproj
spec:
  args:
  - name: service-name
  metrics:
  - name: integration-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            spec:
              containers:
              - name: integration-test
                image: ghcr.io/jettisonproj/rollouts-demo-integration-test:2fb66d654b6b9e0527714f6ee2b5d5f80022faf4
                args:
                - "./integration-test.sh"
                - "http://{{args.service-name}}"
              restartPolicy: Never
