apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-test
  namespace: rollouts-demo
spec:
  args:
  - name: service-name
  metrics:
  - name: integration-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            spec:
              containers:
              - name: integration-test
                image: ghcr.io/osoriano/rollouts-demo-integration-test:0927e8a2dd234165d5499cf74dcbf3faa15823df
                args:
                - "./integration-test.sh"
                - "http://{{args.service-name}}"
              restartPolicy: Never
